# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# kube-state-metrics configuration
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  metricLabelsAllowList:
    - pods=[*]
    - deployments=[*]
    - nodes=[*]
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true