# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if not (eq .Values.namespace "default") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- end }}
