# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

image:
  repository: nvcr.io/nvidia/k8s/cuda-sample
  tag: vectoradd-cuda10.2
  pullPolicy: IfNotPresent
